<?php
/*
 * NewApiLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 07/01/2016
 */

namespace NewApiLib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'http://api.digitalnz.org';

    //Your API Key
    //TODO: Replace the $apiKey with an appropriate value
    public static $apiKey = 'TODO: Replace';

}
